name: Main

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-3.12-${{ hashFiles('poetry.lock') }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 1.7.1

      - name: Install Dependencies
        run: poetry install

      - name: Black
        run: poetry run black --check heroku_scheduled_scaling tests stubs

      - name: mypy
        run: poetry run mypy heroku_scheduled_scaling tests stubs

      - name: ruff
        run: poetry run ruff check heroku_scheduled_scaling tests stubs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-3.12-${{ hashFiles('poetry.lock') }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 1.7.1

      - name: Install Dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest -v

  build-deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ github.repository_owner }}/heroku-scheduled-scaling:latest
